'use strict';
const model = require('../models');

module.exports = {
  up: (queryInterface, Sequelize) => {
      return model.users.bulkCreate([{
        email: 'user1@banque-de-savoie.fr',
        password: 'Azer123',
        gender: 'male',
        age_range: '-30',
        seniority: '-5',
        role: 'client',
        is_active: 1,
        business_focus: 'Corporate and Investment banking',
        createdAt: '2019-01-09 10:00:00',
        updatedAt: '2019-01-09 10:00:00',
        agencyId: 1,
        companyId: 14,
        poleId: 1,
      },{
        email: 'user2@bpca.banquepopulaire.fr',
        password: 'Azer123',
        gender: 'male',
        age_range: '30-39',
        seniority: '5-9',
        role: 'client',
        is_active: 1,
        business_focus: 'Fintech and start-up',
        createdAt: '2019-01-09 10:00:00',
        updatedAt: '2019-01-09 10:00:00',
        agencyId: 43,
        companyId: 37,
        poleId: 2,
      },{
        email: 'user3@banquebcp.fr',
        password: 'Azer123',
        gender: 'female',
        age_range: '40-49',
        seniority: '10-14',
        role: 'client',
        is_active: 1,
        business_focus: 'Insurance',
        createdAt: '2019-01-09 10:00:00',
        updatedAt: '2019-01-09 10:00:00',
        agencyId: 112,
        companyId: 51,
        poleId: 3,
      },{
        email: 'user4@ceacp.caisse-epargne.fr',
        password: 'Azer123',
        gender: 'female',
        age_range: '50-59',
        seniority: '15-19',
        role: 'client',
        is_active: 1,
        business_focus: 'Private Banking',
        createdAt: '2019-01-09 10:00:00',
        updatedAt: '2019-01-09 10:00:00',
        agencyId: 104,
        companyId: 41,
        poleId: 4,
      },{
        email: 'user5@bnpparibas.com',
        password: 'Azer123',
        gender: 'female',
        age_range: '-30',
        seniority: '-5',
        role: 'client',
        is_active: 1,
        business_focus: 'Retail Banking',
        createdAt: '2019-01-09 10:00:00',
        updatedAt: '2019-01-09 10:00:00',
        agencyId: 29,
        companyId: 28,
        poleId: 5,
      },{
        email: 'user6@bnpparibas-pf.com',
        password: 'Azer123',
        gender: 'female',
        age_range: '-30',
        seniority: '-5',
        role: 'client',
        is_active: 1,
        business_focus: 'Specialized Financial Services',
        createdAt: '2019-01-09 10:00:00',
        updatedAt: '2019-01-09 10:00:00',
        agencyId: 115,
        companyId: 53,
        poleId: 1,
      },{
        email: 'super_admin1@exton.com',
        password: 'Azer123',
        gender: 'female',
        age_range: '-30',
        seniority: '-5',
        role: 'super_admin',
        is_active: 1,
        business_focus: 'Specialized Financial Services',
        createdAt: '2019-01-09 10:00:00',
        updatedAt: '2019-01-09 10:00:00',
        agencyId: 13,
        companyId: 14,
        poleId: 1,
      },{
        email: 'admin1@exton.com',
        password: 'Azer123',
        gender: 'female',
        age_range: '-30',
        seniority: '-5',
        role: 'admin',
        is_active: 1,
        business_focus: 'Specialized Financial Services',
        createdAt: '2019-01-09 10:00:00',
        updatedAt: '2019-01-09 10:00:00',
        agencyId: 13,
        companyId: 14,
        poleId: 1,
      },], {});
  },

  down: (queryInterface, Sequelize) => {
      return queryInterface.bulkDelete('users', null, {});
  }
};
